### ISSUE TITLE
Requires valgrind to be installed even when just importing `actors` and not `actors/valgrind`

### ISSUE THREAD

**Issue by ajusa** [zevv/nimactors#5]
I assume it's caused by https://github.com/zevv/actors/blob/1fcf2e029c271d0c925218e026f7abffa6cc9506/actors/pool.nim#L9

It's a bit inconvenient to install a memory debugger/profiler to use the best actor library in the Nim ecosystem :smile:

**Comment by zevv** [comment]
Yeah, well, the game changes of course when the best actor library in the Nim ecosystem suddenly gets *users* eh, I never planned on that!

Joking aside, I'm open to any suggestions on how to make this more convenient (less inconvenient?) for you and others, but I think tight integration with Valgrind and asan/tsan  is absolutely essential to make the actors lib work at all: doing threading in Nim is finicky as hell, and we have seen memory model rules getting violated in a dozen different ways, at least. I guess the obvious solutions would be to put the valgrind-related stuff in `when` blocks and define some symbol that enables them again in the test suite.

If you are bored enough and could provide a patch for that, I'd be happy to apply it; if not I can pick this up someday, but no promises that'll be anytime soon.

**Comment by disruptek** [comment]
I do it like this:
https://github.com/disruptek/insideout/blob/master/insideout/valgrind.nim
...which makes it into a compile-time define and allows this to work correctly in generic contexts.
